version: '2'
services:
    frontdesk-app:
        image: frontdesk
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://frontdesk-mysql:3306/frontdesk?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    frontdesk-mysql:
        extends:
            file: mysql.yml
            service: frontdesk-mysql
